# Generated by Django 4.2.2 on 2023-07-20 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0002_alter_post_category_alter_reply_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='募集', on_delete=django.db.models.deletion.PROTECT, to='snsapp.category', verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='category',
            field=models.ForeignKey(default='返信', on_delete=django.db.models.deletion.PROTECT, to='snsapp.category', verbose_name='カテゴリー'),
        ),
    ]
