# Generated by Django 4.2.2 on 2023-07-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0003_alter_post_category_alter_reply_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
