# Generated by Django 4.2.2 on 2023-07-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0004_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
