# Generated by Django 4.2.2 on 2023-07-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0006_remove_post_image_remove_post_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, choices=[('r', 'R科'), ('s', 'S科'), ('w', 'W科'), ('c', 'C科'), ('a', 'A科'), ('m', 'M科'), ('e', 'E科'), ('d', 'D科'), ('k', 'K科'), ('v', 'V科'), ('u', 'U科')], max_length=10),
        ),
    ]
